name: Build and push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and push image
      run: |
        docker build -t my-image .
        docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
        docker tag my-image "$DOCKER_USERNAME/my-image:latest"
        docker push "$DOCKER_USERNAME/my-image:latest"
