name: node:14-alpine

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          username: USERNAME
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          repository: REPOSITORY_NAME
          tags: latest
